### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### ISSUE THREAD

**Issue by Ayx03** [GamerNoTitle/MHYY-AutoCheckin#20]
*needs to be done before June
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by GamerNoTitle** [comment]
https://github.com/GamerNoTitle/MHYY-AutoCheckin/pull/19

**Comment by Ayx03** [comment]
> #19

![IMG_20230125_232014](https://user-images.githubusercontent.com/75155322/214776836-30dcd285-f8ff-4f31-9926-028c0cc5e623.jpg)
这是两个不同的问题，Blog 说 set-output 6 月 1 日起才会开始报错

**Comment by GamerNoTitle** [comment]
= = 我以为你两个都改了呢

**Comment by GamerNoTitle** [comment]
我看了一下这个文档https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
然后我再去看了一下我的Action文件 https://github.com/GamerNoTitle/MHYY-AutoCheckin/blob/master/.github/workflows/AutoCheckin.yml
我好像没有用到Github的`set-output`呀……我这个里面步骤与步骤之间也不需要参数传递
我这里应该是不用改啥的 如果到时候真的要改的话那就61报错以后再看吧

**Comment by Ayx03** [comment]
> 我看了一下这个文档https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 然后我再去看了一下我的Action文件 https://github.com/GamerNoTitle/MHYY-AutoCheckin/blob/master/.github/workflows/AutoCheckin.yml 我好像没有用到Github的`set-output`呀……我这个里面步骤与步骤之间也不需要参数传递 我这里应该是不用改啥的 如果到时候真的要改的话那就61报错以后再看吧

我也很奇怪，可能把标准输入输出去掉只留推送就行了吧
